create sequence hibernate_sequence start with 1 increment by 1;

create table category (id bigint generated by default as identity, name varchar(128) not null, primary key (id));
create table comment (id bigint generated by default as identity, text varchar(128) not null, parent_post_id bigint not null, parent_user_id bigint not null, primary key (id));
create table post (id bigint generated by default as identity, date timestamp not null, text varchar(128) not null, title varchar(64) not null, category_id bigint, parent_user_id bigint not null, primary key (id));
create table user_roles (user_id bigint not null, roles varchar(255));
create table users (id bigint generated by default as identity, counter integer not null, email varchar(255) not null, enabled boolean not null, first_name varchar(128) not null, password varchar(255), sur_name varchar(128) not null, primary key (id));
alter table category add constraint UK_46ccwnsi9409t36lurvtyljak unique (name);
alter table users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table comment add constraint FKrpa85a2mesc4ngwdavipirdr5 foreign key (parent_post_id) references post;
alter table comment add constraint FKsuw8ab67t2o0csor8wiagkmvk foreign key (parent_user_id) references users;
alter table post add constraint FKg6l1ydp1pwkmyj166teiuov1b foreign key (category_id) references category;
alter table post add constraint FKj8r907486j903fn0fil1av95g foreign key (parent_user_id) references users;
alter table user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users;